spring.application.name=gamefinder

spring.datasource.url=jdbc:h2:mem:gamefinderdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=file:data.sql
spring.sql.init.mode=always